import API_CONTRACTS from "./api-contracts";
import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "consumer-app",
    name: "Consumer Mobile App",
    icon: "📱",
    description:
      "The primary customer-facing application for ordering and profile management.",
    docs: [
      {
        id: "c1",
        title: "Authentication Flow",
        slug: "auth-flow",
        category: "Core",
        lastUpdated: "2024-03-20",
        contentPath: "/docs/consumer/auth-flow.md",
      },
      {
        id: "c2",
        title: "Order Lifecycle",
        slug: "order-lifecycle",
        category: "Business Logic",
        lastUpdated: "2024-03-22",
        contentPath: "/docs/consumer/order-lifecycle.md",
      },
    ],
  },
  {
    id: "delivery-app",
    name: "Delivery Partner App",
    icon: "🛵",
    description:
      "Logistics application for couriers to manage tasks and navigate to locations.",
    docs: [
      {
        id: "d1",
        title: "Real-time Tracking",
        slug: "tracking",
        category: "Infrastructure",
        lastUpdated: "2024-03-15",
        contentPath: "/docs/delivery/tracking.md",
      },
    ],
  },
  {
    id: "backend-gateway",
    name: "API Gateway",
    icon: "☁️",
    description:
      "The central hub for all microservices, handling routing and security.",
    docs: [
      {
        id: "auth",
        title: "Authentication",
        slug: "auth-flow",
        category: "Security",
        lastUpdated: "2026-02-15",
        contentPath: "/docs/backend/auth/auth-flow.md",
      },
      {
        id: "order-entities",
        title: "Order Entities",
        slug: "order-entities",
        category: "Business",
        lastUpdated: "2026-02-15",
        contentPath: "/docs/backend/order/order-entities.md",
      },
      {
        id: "order-create",
        title: "Order Creation LLD (Draft)",
        slug: "order-create",
        category: "Business",
        lastUpdated: "2026-02-16",
        contentPath: "/docs/backend/order/order-create.md",
      },
      {
        id: "order-status-mutation",
        title: "Order Status Mutation",
        slug: "order-status-mutation",
        category: "Business",
        lastUpdated: "2026-02-19",
        contentPath: "/docs/backend/order/order-status-update.md",
      },
      {
        id: "order-history",
        title: "Order History",
        slug: "order-history",
        category: "Business",
        lastUpdated: "2026-02-19",
        contentPath: "/docs/backend/order/order-history.md",
      },
      {
        id: "pricing",
        title: "Pricing & Terms",
        slug: "pricing",
        category: "Business",
        lastUpdated: "2026-02-19",
        contentPath: "/docs/backend/order/pricing.md",
      },
      {
        id: "searchanddiscovery",
        title: "Recommendations",
        slug: "search",
        category: "Search & Discovery",
        lastUpdated: "2026-03-15",
        contentPath:
          "/docs/backend/search/pharmacy-discovery-and-recommendations.md",
      },
      {
        id: "cart-details",
        title: "Cart Details",
        slug: "cart-details",
        category: "Business",
        lastUpdated: "2026-05-31",
        contentPath: "/docs/backend/cart/cart-details.md",
      },
      {
        id: "delivery-overview",
        title: "Overview",
        slug: "delivery-overview",
        category: "Delivery",
        lastUpdated: "2026-06-26",
        contentPath: "/docs/backend/delivery/README.md",
      },
      {
        id: "delivery-hld",
        title: "HLD",
        slug: "delivery-hld",
        category: "Delivery",
        lastUpdated: "2026-06-26",
        contentPath: "/docs/backend/delivery/hld.md",
      },
      {
        id: "delivery-state-machines",
        title: "Status & State Machines",
        slug: "delivery-state-machines",
        category: "Delivery",
        lastUpdated: "2026-06-26",
        contentPath: "/docs/backend/delivery/order-status-and-state-machines.md",
      },
      {
        id: "delivery-data-model",
        title: "Data Model (Postgres & Redis)",
        slug: "delivery-data-model",
        category: "Delivery",
        lastUpdated: "2026-06-26",
        contentPath: "/docs/backend/delivery/data-model.md",
      },
      {
        id: "delivery-matching",
        title: "Matching & Assignment (LLD)",
        slug: "delivery-matching",
        category: "Delivery",
        lastUpdated: "2026-06-26",
        contentPath: "/docs/backend/delivery/matching-and-assignment.md",
      },
      {
        id: "delivery-offer-lifecycle",
        title: "Offer Lifecycle & Scheduler (LLD)",
        slug: "delivery-offer-lifecycle",
        category: "Delivery",
        lastUpdated: "2026-06-26",
        contentPath: "/docs/backend/delivery/offer-lifecycle-and-scheduler.md",
      },
      {
        id: "delivery-notifications",
        title: "Notifications (FCM)",
        slug: "delivery-notifications",
        category: "Delivery",
        lastUpdated: "2026-06-26",
        contentPath: "/docs/backend/delivery/notifications-fcm.md",
      },
      {
        id: "delivery-api-contracts",
        title: "API Contracts",
        slug: "delivery-api-contracts",
        category: "Delivery",
        lastUpdated: "2026-06-26",
        contentPath: "/docs/backend/delivery/api-contracts.md",
      },
      {
        id: "delivery-modularization",
        title: "Modularization & Migration",
        slug: "delivery-modularization",
        category: "Delivery",
        lastUpdated: "2026-06-26",
        contentPath: "/docs/backend/delivery/modularization-and-migration.md",
      },
      {
        id: "delivery-edge-cases",
        title: "Edge Cases & Failure Handling",
        slug: "delivery-edge-cases",
        category: "Delivery",
        lastUpdated: "2026-06-26",
        contentPath: "/docs/backend/delivery/edge-cases-and-failure-handling.md",
      },
      {
        id:"delivery-admin-api",
        title:"Admin APIS For Delivery",
        slug:"delivery-admin-api",
        category:"Delivery",
        lastUpdated:"2026-07-19",
        contentPath:"/docs/backend/delivery/admin-api.md"
      },
      {
        id: "delivery-assumptions",
        title: "Assumptions & Decisions",
        slug: "delivery-assumptions",
        category: "Delivery",
        lastUpdated: "2026-06-26",
        contentPath: "/docs/backend/delivery/assumptions-and-decisions.md",
      },
      ...API_CONTRACTS,
    ],
  },
  {
    id: "ideas",
    name: "Product Ideas",
    icon: "💡",
    description:
      "Early-stage product ideas captured before they get promoted into specs.",
    docs: [
      {
        id: "digital-prescriptions",
        title: "Digital Prescription Network",
        slug: "digital-prescriptions",
        category: "Idea",
        lastUpdated: "2026-05-30",
        contentPath: "/docs/ideas/digital-prescriptions.md",
      },
    ],
  },
];
